// Seed data for clinics, staff, issues, upcoming risks, and throughput

import {
  Clinic,
  Issue,
  IssueStatus,
  Severity,
  StaffMember,
  StalenessState,
  ThroughputData,
  UpcomingRisk,
  VerificationType,
} from "./types";

const now = new Date();

function daysFromNow(days: number): string {
  const d = new Date(now);
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

function daysAgo(days: number): string {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

// Clinics participating in the HealthGuard pilot.
export const clinics: Clinic[] = [
  {
    id: "clinic-riverside",
    name: "Riverside Clinic",
    location: "North District",
  },
  {
    id: "clinic-eastside",
    name: "Eastside Medical Centre",
    location: "East District",
  },
  {
    id: "clinic-northpoint",
    name: "North Point Clinic",
    location: "North District",
  },
  {
    id: "clinic-centralhub",
    name: "Central Health Hub",
    location: "Central District",
  },
];

// Clinical and administrative staff who can own compliance actions.
export const staffMembers: StaffMember[] = [
  {
    id: "staff-1",
    name: "Dr. Maya Chen",
    role: "Medical Director",
    email: "maya.chen@riverside-clinic.example",
    phone: "+1 (555) 210-3489",
    clinicId: "clinic-riverside",
  },
  {
    id: "staff-2",
    name: "Alex Martinez",
    role: "Clinic Administrator",
    email: "alex.martinez@riverside-clinic.example",
    phone: "+1 (555) 210-1123",
    clinicId: "clinic-riverside",
  },
  {
    id: "staff-3",
    name: "Dr. Priya Nair",
    role: "Senior Practitioner",
    email: "priya.nair@eastside-medical.example",
    phone: "+1 (555) 481-9320",
    clinicId: "clinic-eastside",
  },
  {
    id: "staff-4",
    name: "Jordan Blake",
    role: "Nurse Practitioner",
    email: "jordan.blake@eastside-medical.example",
    phone: "+1 (555) 481-7741",
    clinicId: "clinic-eastside",
  },
  {
    id: "staff-5",
    name: "Dr. Samuel Ortiz",
    role: "Senior Practitioner",
    email: "samuel.ortiz@north-point.example",
    phone: "+1 (555) 694-2278",
    clinicId: "clinic-northpoint",
  },
  {
    id: "staff-6",
    name: "Lena Hoffmann",
    role: "Clinic Administrator",
    email: "lena.hoffmann@north-point.example",
    phone: "+1 (555) 694-8890",
    clinicId: "clinic-northpoint",
  },
  {
    id: "staff-7",
    name: "Dr. Amir Rahman",
    role: "Medical Director",
    email: "amir.rahman@central-health-hub.example",
    phone: "+1 (555) 307-4412",
    clinicId: "clinic-centralhub",
  },
  {
    id: "staff-8",
    name: "Nina Patel",
    role: "Nurse Practitioner",
    email: "nina.patel@central-health-hub.example",
    phone: "+1 (555) 307-9821",
    clinicId: "clinic-centralhub",
  },
];

// Core issue queue representing a realistic mix of critical, operational, minor, and resolved work.
export const issues: Issue[] = [
  {
    id: "issue-1",
    typeCode: "EXP-LIC-01",
    title: "Expired practitioner licence - Dr. Maya Chen",
    description:
      "Primary state medical licence for Dr. Chen expired yesterday. No patient-facing shifts should be scheduled until reactivation is confirmed.",
    severity: Severity.Critical,
    status: IssueStatus.Flagged,
    clinicId: "clinic-riverside",
    assigneeId: "staff-2",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 3,
    dueDate: daysFromNow(1),
    delegatedAt: null,
    nudgedAt: null,
    createdAt: daysAgo(2),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-2",
    typeCode: "EXP-DEA-01",
    title: "Expired DEA registration - Dr. Priya Nair",
    description:
      "DEA registration for controlled substances lapsed last week. Electronic prescribing has been blocked until renewal documentation is uploaded.",
    severity: Severity.Critical,
    status: IssueStatus.Flagged,
    clinicId: "clinic-eastside",
    assigneeId: "staff-3",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 5,
    dueDate: daysFromNow(2),
    delegatedAt: null,
    nudgedAt: null,
    createdAt: daysAgo(5),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-3",
    typeCode: "INC-RPT-01",
    title: "Overdue incident report - medication variance",
    description:
      "Medication variance at North Point involving high-alert insulin has not yet been documented in the safety reporting system.",
    severity: Severity.Critical,
    status: IssueStatus.Delegated,
    clinicId: "clinic-northpoint",
    assigneeId: "staff-6",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 2,
    dueDate: daysFromNow(-1),
    delegatedAt: daysAgo(8),
    nudgedAt: daysAgo(2),
    createdAt: daysAgo(10),
    stalenessState: StalenessState.Stale,
  },
  {
    id: "issue-4",
    typeCode: "EQP-FAIL-01",
    title: "Defibrillator safety inspection failed",
    description:
      "Annual safety inspection for defibrillator in Riverside trauma bay failed due to battery performance below threshold.",
    severity: Severity.Critical,
    status: IssueStatus.Delegated,
    clinicId: "clinic-riverside",
    assigneeId: "staff-1",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 1,
    dueDate: daysFromNow(0),
    delegatedAt: daysAgo(3),
    nudgedAt: null,
    createdAt: daysAgo(3),
    stalenessState: StalenessState.Nudged,
  },
  {
    id: "issue-5",
    typeCode: "EXP-LIC-02",
    title: "Licence expiring within 30 days - Dr. Samuel Ortiz",
    description:
      "Primary medical licence for Dr. Ortiz will expire in 24 days. Renewal packet has not yet been submitted.",
    severity: Severity.Operational,
    status: IssueStatus.Flagged,
    clinicId: "clinic-northpoint",
    assigneeId: "staff-6",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 7,
    dueDate: daysFromNow(20),
    delegatedAt: null,
    nudgedAt: null,
    createdAt: daysAgo(4),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-6",
    typeCode: "TRN-HIPAA-01",
    title: "HIPAA annual training overdue - front desk staff",
    description:
      "Three front desk coordinators at Eastside have not completed this year’s HIPAA privacy and security modules.",
    severity: Severity.Operational,
    status: IssueStatus.Delegated,
    clinicId: "clinic-eastside",
    assigneeId: "staff-4",
    verificationType: VerificationType.Auto,
    estimatedResolutionDays: 5,
    dueDate: daysFromNow(5),
    delegatedAt: daysAgo(6),
    nudgedAt: daysAgo(1),
    createdAt: daysAgo(7),
    stalenessState: StalenessState.Nudged,
  },
  {
    id: "issue-7",
    typeCode: "EQP-MNT-01",
    title: "Infusion pump maintenance overdue",
    description:
      "Two infusion pumps at Central Health Hub are overdue for quarterly maintenance by biomedical engineering.",
    severity: Severity.Operational,
    status: IssueStatus.InReview,
    clinicId: "clinic-centralhub",
    assigneeId: "staff-7",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 2,
    dueDate: daysFromNow(4),
    delegatedAt: daysAgo(3),
    nudgedAt: null,
    createdAt: daysAgo(4),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-8",
    typeCode: "CRD-GAP-01",
    title: "Credential not on file - locum tenens physician",
    description:
      "Board certification letter for locum cardiologist working at Riverside is missing from the credentialing file.",
    severity: Severity.Operational,
    status: IssueStatus.Flagged,
    clinicId: "clinic-riverside",
    assigneeId: "staff-2",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 6,
    dueDate: daysFromNow(10),
    delegatedAt: null,
    nudgedAt: null,
    createdAt: daysAgo(1),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-9",
    typeCode: "BGC-01",
    title: "Background check expired - per diem nurse",
    description:
      "Routine background check for per diem nurse at Eastside expired last month; access to paediatrics unit should be restricted.",
    severity: Severity.Operational,
    status: IssueStatus.Delegated,
    clinicId: "clinic-eastside",
    assigneeId: "staff-3",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 4,
    dueDate: daysFromNow(3),
    delegatedAt: daysAgo(5),
    nudgedAt: null,
    createdAt: daysAgo(6),
    stalenessState: StalenessState.Stale,
  },
  {
    id: "issue-10",
    typeCode: "POL-ACK-01",
    title: "Policy acknowledgment missing - opioid prescribing policy",
    description:
      "Four prescribers at Central Health Hub have not acknowledged the updated opioid stewardship policy.",
    severity: Severity.Operational,
    status: IssueStatus.InReview,
    clinicId: "clinic-centralhub",
    assigneeId: "staff-7",
    verificationType: VerificationType.Auto,
    estimatedResolutionDays: 3,
    dueDate: daysFromNow(6),
    delegatedAt: daysAgo(2),
    nudgedAt: null,
    createdAt: daysAgo(3),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-11",
    typeCode: "HR-FILE-01",
    title: "Incomplete HR file - medical assistant",
    description:
      "Immunization record and I-9 documentation missing for newly hired medical assistant at Riverside.",
    severity: Severity.Minor,
    status: IssueStatus.Flagged,
    clinicId: "clinic-riverside",
    assigneeId: "staff-2",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 10,
    dueDate: daysFromNow(14),
    delegatedAt: null,
    nudgedAt: null,
    createdAt: daysAgo(2),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-12",
    typeCode: "TRN-OPT-01",
    title: "Optional advanced airway training not completed",
    description:
      "Two urgent care physicians at North Point have not yet completed optional advanced airway workshop.",
    severity: Severity.Minor,
    status: IssueStatus.Delegated,
    clinicId: "clinic-northpoint",
    assigneeId: "staff-5",
    verificationType: VerificationType.Auto,
    estimatedResolutionDays: 14,
    dueDate: daysFromNow(21),
    delegatedAt: daysAgo(3),
    nudgedAt: null,
    createdAt: daysAgo(3),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-13",
    typeCode: "EQP-CAL-01",
    title: "Calibration record incomplete - vital signs monitor",
    description:
      "Calibration log for vital signs monitor in Central Health Hub triage bay does not include technician signature.",
    severity: Severity.Minor,
    status: IssueStatus.Flagged,
    clinicId: "clinic-centralhub",
    assigneeId: "staff-8",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 5,
    dueDate: daysFromNow(9),
    delegatedAt: null,
    nudgedAt: null,
    createdAt: daysAgo(1),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-14",
    typeCode: "FAC-INS-01",
    title: "Routine facility inspection documentation due",
    description:
      "Quarterly environmental rounds checklist for North Point has not yet been uploaded for this quarter.",
    severity: Severity.Minor,
    status: IssueStatus.Delegated,
    clinicId: "clinic-northpoint",
    assigneeId: "staff-6",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 7,
    dueDate: daysFromNow(18),
    delegatedAt: daysAgo(1),
    nudgedAt: null,
    createdAt: daysAgo(1),
    stalenessState: StalenessState.None,
  },
  // Resolved issues kept for reference in analytics and audit trails.
  {
    id: "issue-15",
    typeCode: "EXP-LIC-01",
    title: "Expired licence resolved - Dr. Amir Rahman",
    description:
      "Licence for Dr. Rahman at Central Health Hub was renewed and validated last week.",
    severity: Severity.Critical,
    status: IssueStatus.Resolved,
    clinicId: "clinic-centralhub",
    assigneeId: "staff-7",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 0,
    dueDate: daysAgo(5),
    delegatedAt: daysAgo(10),
    nudgedAt: null,
    createdAt: daysAgo(15),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-16",
    typeCode: "TRN-HIPAA-01",
    title: "HIPAA training completed - Riverside front desk",
    description:
      "All front desk staff at Riverside completed HIPAA modules and attestations recorded.",
    severity: Severity.Operational,
    status: IssueStatus.Resolved,
    clinicId: "clinic-riverside",
    assigneeId: "staff-2",
    verificationType: VerificationType.Auto,
    estimatedResolutionDays: 0,
    dueDate: daysAgo(3),
    delegatedAt: daysAgo(8),
    nudgedAt: null,
    createdAt: daysAgo(12),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-17",
    typeCode: "EQP-MNT-01",
    title: "Infusion pump maintenance closed",
    description:
      "Quarterly maintenance for infusion pumps at Riverside completed and signed off by biomedical engineer.",
    severity: Severity.Operational,
    status: IssueStatus.Resolved,
    clinicId: "clinic-riverside",
    assigneeId: "staff-1",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 0,
    dueDate: daysAgo(1),
    delegatedAt: daysAgo(5),
    nudgedAt: null,
    createdAt: daysAgo(9),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-18",
    typeCode: "HR-FILE-01",
    title: "HR file completed - Eastside nurse",
    description:
      "All onboarding documentation for newly hired nurse at Eastside has been uploaded and verified.",
    severity: Severity.Minor,
    status: IssueStatus.Resolved,
    clinicId: "clinic-eastside",
    assigneeId: "staff-4",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 0,
    dueDate: daysAgo(2),
    delegatedAt: daysAgo(6),
    nudgedAt: null,
    createdAt: daysAgo(10),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-19",
    typeCode: "POL-ACK-01",
    title: "Opioid stewardship policy acknowledgments completed",
    description:
      "All prescribers at North Point have acknowledged the updated opioid stewardship policy.",
    severity: Severity.Operational,
    status: IssueStatus.Resolved,
    clinicId: "clinic-northpoint",
    assigneeId: "staff-5",
    verificationType: VerificationType.Auto,
    estimatedResolutionDays: 0,
    dueDate: daysAgo(4),
    delegatedAt: daysAgo(9),
    nudgedAt: null,
    createdAt: daysAgo(12),
    stalenessState: StalenessState.None,
  },
  {
    id: "issue-20",
    typeCode: "FAC-INS-01",
    title: "Facility inspection documentation archived",
    description:
      "Previous quarter environmental rounds for Riverside have been archived after QA review.",
    severity: Severity.Minor,
    status: IssueStatus.Resolved,
    clinicId: "clinic-riverside",
    assigneeId: "staff-2",
    verificationType: VerificationType.Manual,
    estimatedResolutionDays: 0,
    dueDate: daysAgo(30),
    delegatedAt: daysAgo(40),
    nudgedAt: null,
    createdAt: daysAgo(45),
    stalenessState: StalenessState.None,
  },
];

// Forward-looking compliance risks based on upcoming expirations and deadlines.
export const upcomingRisks: UpcomingRisk[] = [
  {
    id: "risk-1",
    title: "Practitioner licence renewal window closing",
    clinicId: "clinic-northpoint",
    affectedPerson: "Dr. Samuel Ortiz",
    daysUntilBreach: 5,
    issueTypeCode: "EXP-LIC-02",
  },
  {
    id: "risk-2",
    title: "DEA registration renewal pending board approval",
    clinicId: "clinic-eastside",
    affectedPerson: "Dr. Priya Nair",
    daysUntilBreach: 9,
    issueTypeCode: "EXP-DEA-01",
  },
  {
    id: "risk-3",
    title: "Annual HIPAA refresher window ending",
    clinicId: "clinic-centralhub",
    affectedPerson: "All clinical staff",
    daysUntilBreach: 13,
    issueTypeCode: "TRN-HIPAA-01",
  },
  {
    id: "risk-4",
    title: "Quarterly equipment maintenance cycle cutoff",
    clinicId: "clinic-riverside",
    affectedPerson: "Biomedical engineering team",
    daysUntilBreach: 21,
    issueTypeCode: "EQP-MNT-01",
  },
  {
    id: "risk-5",
    title: "Routine facility inspection window closing",
    clinicId: "clinic-northpoint",
    affectedPerson: "Facilities coordinator",
    daysUntilBreach: 28,
    issueTypeCode: "FAC-INS-01",
  },
];

// Weekly throughput data used for the severity strip trend indicators.
export const throughputData: ThroughputData = {
  resolvedThisWeek: 12,
  newThisWeek: 18,
  resolvedLastWeek: 20,
  newLastWeek: 14,
};

